//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEDBOXMAUI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LEDBOXMAUI.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFORMAZIONI.
        /// </summary>
        public static string about_us {
            get {
                return ResourceManager.GetString("about_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non è possibile utilizzare questa interfaccia perchè il LEDbox è già controllato da un altro utente..
        /// </summary>
        public static string access_denied {
            get {
                return ResourceManager.GetString("access_denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona comando:.
        /// </summary>
        public static string action {
            get {
                return ResourceManager.GetString("action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATTIVITA&apos;.
        /// </summary>
        public static string activity {
            get {
                return ResourceManager.GetString("activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ci sono attività in corso sul LEDbox. Visualizzarle?.
        /// </summary>
        public static string activitydialog {
            get {
                return ResourceManager.GetString("activitydialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funzioni avanzate LEDbox.
        /// </summary>
        public static string advanced_function_ledbox {
            get {
                return ResourceManager.GetString("advanced_function_ledbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animazione.
        /// </summary>
        public static string animation {
            get {
                return ResourceManager.GetString("animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocità.
        /// </summary>
        public static string animation_velocity {
            get {
                return ResourceManager.GetString("animation_velocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un altro processo è già in esecuzione sul LEDbox..
        /// </summary>
        public static string another_diplay_process_execute {
            get {
                return ResourceManager.GetString("another_diplay_process_execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La versione dell&apos;app non è compatibile con questo LEDbox. Aggiornare l&apos;app all&apos;ultima versione disponibile..
        /// </summary>
        public static string app_not_compatible {
            get {
                return ResourceManager.GetString("app_not_compatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sicuro di voler continuare con l&apos;operazione?.
        /// </summary>
        public static string are_you_sure {
            get {
                return ResourceManager.GetString("are_you_sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string audio {
            get {
                return ResourceManager.GetString("audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lampeggiante.
        /// </summary>
        public static string blinking {
            get {
                return ResourceManager.GetString("blinking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blu.
        /// </summary>
        public static string blue {
            get {
                return ResourceManager.GetString("blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulla.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo connessione.
        /// </summary>
        public static string change_connection {
            get {
                return ResourceManager.GetString("change_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lingua.
        /// </summary>
        public static string change_language {
            get {
                return ResourceManager.GetString("change_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambia utente.
        /// </summary>
        public static string change_user {
            get {
                return ResourceManager.GetString("change_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scarica aggiornamento LEDbox.
        /// </summary>
        public static string check_last_ledbox_version {
            get {
                return ResourceManager.GetString("check_last_ledbox_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scegli.
        /// </summary>
        public static string choose {
            get {
                return ResourceManager.GetString("choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona il LEDbox a cui collegarti.
        /// </summary>
        public static string choose_bluetooth {
            get {
                return ResourceManager.GetString("choose_bluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colore.
        /// </summary>
        public static string color_text {
            get {
                return ResourceManager.GetString("color_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurazioni salvate.
        /// </summary>
        public static string config_saved {
            get {
                return ResourceManager.GetString("config_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configura LEDbox.
        /// </summary>
        public static string configure_ledbox {
            get {
                return ResourceManager.GetString("configure_ledbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File eliminati correttamente sul LEDbox..
        /// </summary>
        public static string confirm_deletion {
            get {
                return ResourceManager.GetString("confirm_deletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disinstallare l&apos;elemento selezionato?.
        /// </summary>
        public static string confirm_disinstallation {
            get {
                return ResourceManager.GetString("confirm_disinstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scaricare ed installare l&apos;elemento selezionato?.
        /// </summary>
        public static string confirm_installation {
            get {
                return ResourceManager.GetString("confirm_installation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connetti.
        /// </summary>
        public static string connect {
            get {
                return ResourceManager.GetString("connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avviare la connessione all&apos;ultimo LEDbox a cui ti sei collegato?.
        /// </summary>
        public static string connect_last_ledbox {
            get {
                return ResourceManager.GetString("connect_last_ledbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collegare il device alla rete Wi-Fi in cui è collegato il LEDbox..
        /// </summary>
        public static string connect_to_wifi {
            get {
                return ResourceManager.GetString("connect_to_wifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prima effettuare la connessione al LEDbox..
        /// </summary>
        public static string connecting_before_ledbox {
            get {
                return ResourceManager.GetString("connecting_before_ledbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connessione a LEDbox in corso ....
        /// </summary>
        public static string connecting_ledbox {
            get {
                return ResourceManager.GetString("connecting_ledbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crea playlist.
        /// </summary>
        public static string create_playlist {
            get {
                return ResourceManager.GetString("create_playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creazione del file in corso....
        /// </summary>
        public static string creation_progress {
            get {
                return ResourceManager.GetString("creation_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informazioni su....
        /// </summary>
        public static string credits {
            get {
                return ResourceManager.GetString("credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impostazione corrente: .
        /// </summary>
        public static string current_setting {
            get {
                return ResourceManager.GetString("current_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TESTO LIBERO.
        /// </summary>
        public static string custom_text {
            get {
                return ResourceManager.GetString("custom_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elimina.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elimina tutte le playlist audio sul LEDbox.
        /// </summary>
        public static string delete_playlistaudio {
            get {
                return ResourceManager.GetString("delete_playlistaudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elimina tutte le sequenze di esercizi sul LEDbox.
        /// </summary>
        public static string delete_playlistimage {
            get {
                return ResourceManager.GetString("delete_playlistimage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rete LAN riavviata.
        /// </summary>
        public static string dhcp_restarted {
            get {
                return ResourceManager.GetString("dhcp_restarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per connettersi in Wi-Fi al LEDbox disabilitare i Dati mobili del dispositivo..
        /// </summary>
        public static string disable_mobile_connection {
            get {
                return ResourceManager.GetString("disable_mobile_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnetti.
        /// </summary>
        public static string disconnect {
            get {
                return ResourceManager.GetString("disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per cambiare la lingua ho disconnesso il LEDbox..
        /// </summary>
        public static string disconnect_for_change_language {
            get {
                return ResourceManager.GetString("disconnect_for_change_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disinstallazione.
        /// </summary>
        public static string disinstallation {
            get {
                return ResourceManager.GetString("disinstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scarica ed installa.
        /// </summary>
        public static string download_and_install {
            get {
                return ResourceManager.GetString("download_and_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiornamento LEDbox scaricato correttamente..
        /// </summary>
        public static string download_last_upgrade_completed {
            get {
                return ResourceManager.GetString("download_last_upgrade_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scaricamento lista in corso....
        /// </summary>
        public static string download_list {
            get {
                return ResourceManager.GetString("download_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scarica manuale.
        /// </summary>
        public static string download_manual {
            get {
                return ResourceManager.GetString("download_manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scaricamento in corso....
        /// </summary>
        public static string downloading {
            get {
                return ResourceManager.GetString("downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scaricamento dati di default in corso....
        /// </summary>
        public static string downloading_preinstall {
            get {
                return ResourceManager.GetString("downloading_preinstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplica.
        /// </summary>
        public static string duplicate {
            get {
                return ResourceManager.GetString("duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to elementi.
        /// </summary>
        public static string elements {
            get {
                return ResourceManager.GetString("elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserisci l&apos;indirizzo IP del LEDbox (prova con 172.24.1.1) e riprova a connetterti..
        /// </summary>
        public static string enter_ip_ledbox {
            get {
                return ResourceManager.GetString("enter_ip_ledbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore di comunicazione con il LEDbox.
        /// </summary>
        public static string error_communication {
            get {
                return ResourceManager.GetString("error_communication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore durante la connessione.
        /// </summary>
        public static string error_connection {
            get {
                return ResourceManager.GetString("error_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore durante la connessione a LEDbox.
        /// </summary>
        public static string error_connection_to_ledbox {
            get {
                return ResourceManager.GetString("error_connection_to_ledbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore durante la connessione Bluetooth. Verificare che il LEDbox sia acceso..
        /// </summary>
        public static string error_connection_to_ledbox_bluetooth {
            get {
                return ResourceManager.GetString("error_connection_to_ledbox_bluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore durante lo scaricamento.
        /// </summary>
        public static string error_download {
            get {
                return ResourceManager.GetString("error_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore nella creazione dell&apos;immagine.
        /// </summary>
        public static string error_image {
            get {
                return ResourceManager.GetString("error_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore di lettura.
        /// </summary>
        public static string error_read {
            get {
                return ResourceManager.GetString("error_read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore nel caricamento sul LEDbox..
        /// </summary>
        public static string error_upload {
            get {
                return ResourceManager.GetString("error_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore nella creazione del pacchetto dei file multimediali..
        /// </summary>
        public static string error_zip {
            get {
                return ResourceManager.GetString("error_zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dal tuo dispositivo.
        /// </summary>
        public static string from_local {
            get {
                return ResourceManager.GetString("from_local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string from_online {
            get {
                return ResourceManager.GetString("from_online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galleria.
        /// </summary>
        public static string gallery {
            get {
                return ResourceManager.GetString("gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verde.
        /// </summary>
        public static string green {
            get {
                return ResourceManager.GetString("green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immagini.
        /// </summary>
        public static string image {
            get {
                return ResourceManager.GetString("image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copertina sul LEDbox.
        /// </summary>
        public static string image_cover {
            get {
                return ResourceManager.GetString("image_cover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immagini.
        /// </summary>
        public static string image_video {
            get {
                return ResourceManager.GetString("image_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copertina.
        /// </summary>
        public static string image_wait {
            get {
                return ResourceManager.GetString("image_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserisci il nome della playlist.
        /// </summary>
        public static string insert_name_playlist {
            get {
                return ResourceManager.GetString("insert_name_playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserisci il nome della sequenza di esercizi.
        /// </summary>
        public static string insert_name_practice {
            get {
                return ResourceManager.GetString("insert_name_practice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserisci il titolo.
        /// </summary>
        public static string insert_title {
            get {
                return ResourceManager.GetString("insert_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installazione.
        /// </summary>
        public static string installation {
            get {
                return ResourceManager.GetString("installation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installazione completata.
        /// </summary>
        public static string installation_complete {
            get {
                return ResourceManager.GetString("installation_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questa interfaccia può essere utilizzata solo dal primo utente che si è connesso sul LEDbox..
        /// </summary>
        public static string interface_for_only_admin {
            get {
                return ResourceManager.GetString("interface_for_only_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questa interfaccia può essere utilizzata solo con connessioni Bluetooth..
        /// </summary>
        public static string interface_for_only_bluetooth_connection {
            get {
                return ResourceManager.GetString("interface_for_only_bluetooth_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questa interfaccia può essere utilizzata solo con connessioni Wi-Fi..
        /// </summary>
        public static string interface_for_only_wifi_connection {
            get {
                return ResourceManager.GetString("interface_for_only_wifi_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to È presente un&apos;interfaccia più vecchia di quella che si sta installando. Disinstallare la vecchia interfaccia?.
        /// </summary>
        public static string interface_yet_present {
            get {
                return ResourceManager.GetString("interface_yet_present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indirizzo IP (LAN).
        /// </summary>
        public static string ip_lan {
            get {
                return ResourceManager.GetString("ip_lan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indirizzo IP (Wifi).
        /// </summary>
        public static string ip_wifi {
            get {
                return ResourceManager.GetString("ip_wifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questo elemento è presente solo sul LEDbox. È possibile solo avviare / mettere in pausa / interropere l&apos;esecuzione..
        /// </summary>
        public static string item_only_on_ledbox {
            get {
                return ResourceManager.GetString("item_only_on_ledbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEDbox connesso correttamente..
        /// </summary>
        public static string ledbox_connected {
            get {
                return ResourceManager.GetString("ledbox_connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funzionalità LEDbox.
        /// </summary>
        public static string ledbox_functions {
            get {
                return ResourceManager.GetString("ledbox_functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessun LEDbox trovato..
        /// </summary>
        public static string ledbox_not_found {
            get {
                return ResourceManager.GetString("ledbox_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ricerca del LEDbox in corso....
        /// </summary>
        public static string ledbox_search {
            get {
                return ResourceManager.GetString("ledbox_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sto riavviando il LEDbox per completare l&apos;aggiornamento..
        /// </summary>
        public static string ledbox_updated {
            get {
                return ResourceManager.GetString("ledbox_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessuna sequenza di esercizi presente sul LEDbox corrente..
        /// </summary>
        public static string list_empty_practice_remote {
            get {
                return ResourceManager.GetString("list_empty_practice_remote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caricamento in corso ....
        /// </summary>
        public static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciao, inserisci qui i tuoi dati poi premi su OK..
        /// </summary>
        public static string login_intro {
            get {
                return ResourceManager.GetString("login_intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to suono lungo.
        /// </summary>
        public static string long_beep {
            get {
                return ResourceManager.GetString("long_beep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to suoni lunghi.
        /// </summary>
        public static string long_beeps {
            get {
                return ResourceManager.GetString("long_beeps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indirizzo IP (master) non valido.
        /// </summary>
        public static string master_ip_not_valid {
            get {
                return ResourceManager.GetString("master_ip_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEGNAPUNTI.
        /// </summary>
        public static string match_score {
            get {
                return ResourceManager.GetString("match_score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memoria LEDbox.
        /// </summary>
        public static string memory_ledbox {
            get {
                return ResourceManager.GetString("memory_ledbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando inviato al LEDbox.
        /// </summary>
        public static string message_sended {
            get {
                return ResourceManager.GetString("message_sended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruolo nella comunicazione.
        /// </summary>
        public static string mode_execute {
            get {
                return ResourceManager.GetString("mode_execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modalità display.
        /// </summary>
        public static string modifier_layout {
            get {
                return ResourceManager.GetString("modifier_layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sposta giù.
        /// </summary>
        public static string move_down {
            get {
                return ResourceManager.GetString("move_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sposta su.
        /// </summary>
        public static string move_up {
            get {
                return ResourceManager.GetString("move_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&apos; necessario abilitare la Geolocalizzazione per la connessione WiFi..
        /// </summary>
        public static string must_enabled_location {
            get {
                return ResourceManager.GetString("must_enabled_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indirizzo IP gateway (sezione Network) non valido..
        /// </summary>
        public static string network_gateway_not_valid {
            get {
                return ResourceManager.GetString("network_gateway_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indirizzo IP (sezione Network) non valido..
        /// </summary>
        public static string network_ip_not_valid {
            get {
                return ResourceManager.GetString("network_ip_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modalità di collegamento LAN.
        /// </summary>
        public static string network_modality {
            get {
                return ResourceManager.GetString("network_modality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indirizzo Subnet (sezione Network) non valido.
        /// </summary>
        public static string network_subnet_not_valid {
            get {
                return ResourceManager.GetString("network_subnet_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuovo versione firmware del LEDbox scaricato..
        /// </summary>
        public static string new_firmware_ledbox_downloaded {
            get {
                return ResourceManager.GetString("new_firmware_ledbox_downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessun LEDbox trovato..
        /// </summary>
        public static string no_device_bluetooth {
            get {
                return ResourceManager.GetString("no_device_bluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessun elemento inserito nella lista..
        /// </summary>
        public static string no_elements {
            get {
                return ResourceManager.GetString("no_elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connessione ad internet assente..
        /// </summary>
        public static string no_internet {
            get {
                return ResourceManager.GetString("no_internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devi disattivare la connessione Wifi del LEDbox e collegarti ad una rete internet (Wifi o mobile) per accedere ai contenuti online.
        /// </summary>
        public static string no_internet_wifi_direct {
            get {
                return ResourceManager.GetString("no_internet_wifi_direct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La versione del software del LEDbox non è compatibile con questa App..
        /// </summary>
        public static string no_ledbox_compatible {
            get {
                return ResourceManager.GetString("no_ledbox_compatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connettiti ad un LEDbox per accedere alla sua sequenza di esercizi..
        /// </summary>
        public static string no_ledbox_connect_to_practice_remote {
            get {
                return ResourceManager.GetString("no_ledbox_connect_to_practice_remote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nessuno.
        /// </summary>
        public static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessun file inserito nella playlist..
        /// </summary>
        public static string none_playlist_item {
            get {
                return ResourceManager.GetString("none_playlist_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessun esercizio inserito nella sequenza..
        /// </summary>
        public static string none_practice_item {
            get {
                return ResourceManager.GetString("none_practice_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo sul LEDbox.
        /// </summary>
        public static string on_ledbox {
            get {
                return ResourceManager.GetString("on_ledbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to È disponibile un nuovo aggiornamento per LEDbox. Scaricarlo ora?.
        /// </summary>
        public static string online_new_upgrade_ledbox {
            get {
                return ResourceManager.GetString("online_new_upgrade_ledbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostra i parametri.
        /// </summary>
        public static string open_layout_parameters {
            get {
                return ResourceManager.GetString("open_layout_parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostra copertina.
        /// </summary>
        public static string open_layout_waiting {
            get {
                return ResourceManager.GetString("open_layout_waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEDbox Store.
        /// </summary>
        public static string open_store {
            get {
                return ResourceManager.GetString("open_store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arancione.
        /// </summary>
        public static string orange {
            get {
                return ResourceManager.GetString("orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pausa.
        /// </summary>
        public static string pause {
            get {
                return ResourceManager.GetString("pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to avvia.
        /// </summary>
        public static string play {
            get {
                return ResourceManager.GetString("play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAYLIST.
        /// </summary>
        public static string playlist {
            get {
                return ResourceManager.GetString("playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAYLIST (Audio).
        /// </summary>
        public static string playlist_audio {
            get {
                return ResourceManager.GetString("playlist_audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAYLIST (Immagini).
        /// </summary>
        public static string playlist_imagevideo {
            get {
                return ResourceManager.GetString("playlist_imagevideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESERCIZI.
        /// </summary>
        public static string practice {
            get {
                return ResourceManager.GetString("practice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferenze.
        /// </summary>
        public static string preferences {
            get {
                return ResourceManager.GetString("preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esercizi liberi.
        /// </summary>
        public static string preset {
            get {
                return ResourceManager.GetString("preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anteprima.
        /// </summary>
        public static string preview {
            get {
                return ResourceManager.GetString("preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viola.
        /// </summary>
        public static string purple {
            get {
                return ResourceManager.GetString("purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riavvia LEDBox.
        /// </summary>
        public static string reboot {
            get {
                return ResourceManager.GetString("reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per rendere effettive le modifiche riavviare il LEDbox. Riavviarlo ora?.
        /// </summary>
        public static string reboot_app {
            get {
                return ResourceManager.GetString("reboot_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riavvio del LEDbox in corso ....
        /// </summary>
        public static string rebooting {
            get {
                return ResourceManager.GetString("rebooting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rosso.
        /// </summary>
        public static string red {
            get {
                return ResourceManager.GetString("red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azzera.
        /// </summary>
        public static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riavvia rete LAN.
        /// </summary>
        public static string restart_dhcp {
            get {
                return ResourceManager.GetString("restart_dhcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avviare ora l&apos;aggiornamento del LEDbox?.
        /// </summary>
        public static string run_update {
            get {
                return ResourceManager.GetString("run_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salva.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scorrimento (da sotto verso sopra).
        /// </summary>
        public static string scroller_bottom_top {
            get {
                return ResourceManager.GetString("scroller_bottom_top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scorrimento (da sinistra verso destra).
        /// </summary>
        public static string scroller_left_right {
            get {
                return ResourceManager.GetString("scroller_left_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scorrimento (da destra verso sinistra).
        /// </summary>
        public static string scroller_right_left {
            get {
                return ResourceManager.GetString("scroller_right_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scorrimento (da sopra verso sotto).
        /// </summary>
        public static string scroller_top_bottom {
            get {
                return ResourceManager.GetString("scroller_top_bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cercare altri LEDbox nella rete?.
        /// </summary>
        public static string search_other_ledbox {
            get {
                return ResourceManager.GetString("search_other_ledbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ricerca....
        /// </summary>
        public static string searching {
            get {
                return ResourceManager.GetString("searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerca LEDbox.
        /// </summary>
        public static string searching_bluetooth {
            get {
                return ResourceManager.GetString("searching_bluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona la connessione al LEDbox.
        /// </summary>
        public static string select_connection {
            get {
                return ResourceManager.GetString("select_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona la lingua.
        /// </summary>
        public static string select_language {
            get {
                return ResourceManager.GetString("select_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIGURAZIONE.
        /// </summary>
        public static string setting {
            get {
                return ResourceManager.GetString("setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impostazioni.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impostazioni LEDbox.
        /// </summary>
        public static string settings_ledbox {
            get {
                return ResourceManager.GetString("settings_ledbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to suono breve.
        /// </summary>
        public static string short_beep {
            get {
                return ResourceManager.GetString("short_beep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to suoni brevi.
        /// </summary>
        public static string short_beeps {
            get {
                return ResourceManager.GetString("short_beeps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensione.
        /// </summary>
        public static string size_text {
            get {
                return ResourceManager.GetString("size_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selezionare uno sport.
        /// </summary>
        public static string sport_required {
            get {
                return ResourceManager.GetString("sport_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riavvia rete LAN in corso ....
        /// </summary>
        public static string start_dhcp_restart {
            get {
                return ResourceManager.GetString("start_dhcp_restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop.
        /// </summary>
        public static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STORE.
        /// </summary>
        public static string store {
            get {
                return ResourceManager.GetString("store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connessione effettuata correttamente..
        /// </summary>
        public static string success_connection {
            get {
                return ResourceManager.GetString("success_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sicuro di voler disconnettersi dal LEDbox?.
        /// </summary>
        public static string sure_disconnect {
            get {
                return ResourceManager.GetString("sure_disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testo.
        /// </summary>
        public static string text {
            get {
                return ResourceManager.GetString("text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibilità.
        /// </summary>
        public static string time_visibility {
            get {
                return ResourceManager.GetString("time_visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elimina.
        /// </summary>
        public static string trash {
            get {
                return ResourceManager.GetString("trash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TUTTI I FILE MULTIMEDIALI.
        /// </summary>
        public static string trash_all_media {
            get {
                return ResourceManager.GetString("trash_all_media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiornamento LEDbox.
        /// </summary>
        public static string update_ledbox {
            get {
                return ResourceManager.GetString("update_ledbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinstalla aggionamento .
        /// </summary>
        public static string update_to {
            get {
                return ResourceManager.GetString("update_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premi l&apos;icona con il + per aggiungere un nuovo elemento..
        /// </summary>
        public static string use_plus_button {
            get {
                return ResourceManager.GetString("use_plus_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premi l&apos;icona store per scaricare un nuovo segnapunti..
        /// </summary>
        public static string use_store_button {
            get {
                return ResourceManager.GetString("use_store_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome utente.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome utente obbligatorio.
        /// </summary>
        public static string username_required {
            get {
                return ResourceManager.GetString("username_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versione.
        /// </summary>
        public static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string video {
            get {
                return ResourceManager.GetString("video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attenzione.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATTENZIONE: ll LEDbox deve essere acceso da non più di un minuto..
        /// </summary>
        public static string warning_scan_bluetooth {
            get {
                return ResourceManager.GetString("warning_scan_bluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ginnastica.
        /// </summary>
        public static string weight_gym {
            get {
                return ResourceManager.GetString("weight_gym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bianco.
        /// </summary>
        public static string white {
            get {
                return ResourceManager.GetString("white", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modalità di collegamento Wi-Fi.
        /// </summary>
        public static string wifi_modality {
            get {
                return ResourceManager.GetString("wifi_modality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verranno scaricati.
        /// </summary>
        public static string will_be_downloaded {
            get {
                return ResourceManager.GetString("will_be_downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giallo.
        /// </summary>
        public static string yellow {
            get {
                return ResourceManager.GetString("yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hai scaricato l&apos;ultima versione di aggiornamento del LEDbox..
        /// </summary>
        public static string you_download_last_ledbox_upgrade {
            get {
                return ResourceManager.GetString("you_download_last_ledbox_upgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hai già l&apos;ultima versione di aggiornamento del LEDbox..
        /// </summary>
        public static string you_have_last_ledbox_upgrade {
            get {
                return ResourceManager.GetString("you_have_last_ledbox_upgrade", resourceCulture);
            }
        }
    }
}
